{
 "title": "cisco-trex stl_exporter",
 "description": "\n\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cisco-trex Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_util{\r\n  instance=\"10.20.51.149:9362\",\r\n  job=\"ciscotrex-exporter\",\r\n  metric_type=\"global\"\r\n}",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "UP prometheus ciscotrex-exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "up" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rx_util",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "rx_util", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "отображает количество метрик (samples)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "scrape_samples_scraped{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(dp_core_count{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"})",
     "legendFormat": "Total cores"
    },
    {
     "expr": "max(dp_core_count_per_port {instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"})",
     "legendFormat": "Cores per dual-port"
    }
   ]
  },
  {
   "title": " active_sockets",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  active_sockets{\r\n    cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\",\r\n    driver=\"global\",\r\n    instance=\"10.20.51.149:9362\",\r\n    job=\"ciscotrex-exporter\",\r\n    metric_type=\"global\",\r\n    nic=\"global\",\r\n    numa=\"global\",\r\n    port=\"global\"\r\n  }[1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tx_util",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "tx_util", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Суммарную скорость приёма трафика (в битах в секунду, bps) на устройстве TRex по всем портам",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (instance, job)\r\n  /\r\nmax(dp_core_count_per_port{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"}) by (instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (instance, job)\r\n  /\r\nmax(dp_core_count_per_port{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"}) by (instance, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global TX / RX pps",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rx_pps {instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}",
     "legendFormat": "{{port_name}} RX pps"
    },
    {
     "expr": "tx_pps {instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}",
     "legendFormat": "{{port_name}} TX pps"
    },
    {
     "expr": "max(\r\n  tx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}\r\n  -\r\n  rx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}\r\n)",
     "legendFormat": "Packet loss"
    },
    {
     "expr": "rate(queue_full{instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Queue full"
    }
   ]
  },
  { "title": "Global Statistics Port ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Per Port TX / RX bps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"} ",
     "legendFormat": "RX bps for port {{port}}"
    },
    {
     "expr": "tx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"}",
     "legendFormat": "TX bps for port {{port}}"
    }
   ]
  },
  {
   "title": "tx/rx_bps_L1",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rx_bps_L1{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "tx_bps_L1{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"} ",
     "legendFormat": "__auto"
    },
    { "expr": "sum by(instance) (tx_bps_L1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ierrors\\ierrors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ierrors", "legendFormat": "__auto" },
    { "expr": "oerrors", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cixo-trex  STL total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Drop_rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rx_drop_bps{job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (cpu_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_full",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_full", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "obytes / ibytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "packet" } },
   "targets": [
    { "expr": "obytes ", "legendFormat": "__auto" },
    { "expr": "ibytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Global TX / RX bps",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "tx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "rx_bps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rx_drop_bps{job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (cpu_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tx_bps-L2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "tx_bps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rx_bps-L2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "rx_bps", "legendFormat": "__auto" }
   ]
  },
  { "title": "ipackets opackets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "ipackets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    { "expr": "ipackets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "opackets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    { "expr": "opackets", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "rate(ibytes{",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ibytes{\r\n  cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\",\r\n  driver=\"net_iavf\",\r\n  instance=\"10.20.51.149:9362\",\r\n  job=\"ciscotrex-exporter\",\r\n  metric_type=\"per_port\",\r\n  nic=\"Ethernet Adaptive Virtual Function\",\r\n  numa=\"1\",\r\n  port=\"0\"\r\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX/TX PPS per Core",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (instance, job)\r\n  /\r\nmax(dp_core_count_per_port{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"}) by (instance, job)",
     "legendFormat": "{{port}} RX pps"
    },
    {
     "expr": "sum(tx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"global\"}) by (instance, job)\r\n  /\r\nmax(dp_core_count_per_port{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\"}) by (instance, job)",
     "legendFormat": "{{port}} TX pps"
    }
   ]
  },
  {
   "title": "Per Port TX / RX pps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rx_pps  {instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"}",
     "legendFormat": "RX bps for port {{port}}"
    },
    {
     "expr": "tx_pps  {instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"}",
     "legendFormat": "TX bps for port {{port}}"
    },
    {
     "expr": "max(\r\n  (\r\n    tx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"}\r\n    -\r\n    rx_pps{instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\"}\r\n  ) > 0\r\n  or\r\n  vector(0)\r\n)",
     "legendFormat": "Packet loss for port {{port}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "{__name__=\"tx_bps\", cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"tx_bps\", cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tx_pps",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "tx_pps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total_clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "total_clients{port=\"global\", nic=\"global\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total_servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 87 },
   "targets": [
    { "expr": "total_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ipackets driver=\"net_iavf\",",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "ipackets{cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipackets{cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipackets{cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipackets{cpu_type=\"Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz\", driver=\"net_iavf\", instance=\"10.20.51.149:9362\", job=\"ciscotrex-exporter\", metric_type=\"per_port\", nic=\"Ethernet Adaptive Virtual Function\", numa=\"1\", port=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 100 },
   "targets": [
    { "expr": "total_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sys_heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "UP" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}